/**
 * Language Constants
 *
 * All language-related constants and enums for the multilingual support system
 */

// Language categories for navigation
export enum LanguageCategory {
  POPULAR = "popular",
  EUROPE = "europe",
  ASIA = "asia",
  AMERICAS = "americas",
  AFRICA = "africa",
  OCEANIA = "oceania",
  CUSTOM = "custom",
}

// Popular languages for quick selection
export const POPULAR_LANGUAGES = {
  en: "🇺🇸 English",
  ja: "🇯🇵 日本語",
  ko: "🇰🇷 한국어",
  zh: "🇨🇳 中文",
  es: "🇪🇸 Español",
  fr: "🇫🇷 Français",
  de: "🇩🇪 Deutsch",
  ru: "🇷🇺 Русский",
  pt: "🇧🇷 Português",
  hi: "🇮🇳 हिन्दी",
  ar: "🇸🇦 العربية",
  tr: "🇹🇷 Türkçe",
} as const;

// Regional language categories
export const REGIONAL_LANGUAGES = {
  europe: {
    name: "🇪🇺 Europe",
    languages: {
      en: "🇬🇧 English",
      de: "🇩🇪 Deutsch",
      fr: "🇫🇷 Français",
      es: "🇪🇸 Español",
      it: "🇮🇹 Italiano",
      ru: "🇷🇺 Русский",
      pl: "🇵🇱 Polski",
      nl: "🇳🇱 Nederlands",
      sv: "🇸🇪 Svenska",
      no: "🇳🇴 Norsk",
      da: "🇩🇰 Dansk",
      fi: "🇫🇮 Suomi",
      cs: "🇨🇿 Čeština",
      hu: "🇭🇺 Magyar",
      ro: "🇷🇴 Română",
      bg: "🇧🇬 Български",
      hr: "🇭🇷 Hrvatski",
      sk: "🇸🇰 Slovenčina",
      sl: "🇸🇮 Slovenščina",
      et: "🇪🇪 Eesti",
      lv: "🇱🇻 Latviešu",
      lt: "🇱🇹 Lietuvių",
      el: "🇬🇷 Ελληνικά",
      mt: "🇲🇹 Malti",
      ga: "🇮🇪 Gaeilge",
      cy: "🏴󠁧󠁢󠁷󠁬󠁳󠁿 Cymraeg",
      eu: "🏴 Euskera",
      ca: "🏴 Català",
    },
  },
  asia: {
    name: "🌏 Asia",
    languages: {
      zh: "🇨🇳 中文",
      ja: "🇯🇵 日本語",
      ko: "🇰🇷 한국어",
      hi: "🇮🇳 हिन्दी",
      th: "🇹🇭 ไทย",
      vi: "🇻🇳 Tiếng Việt",
      id: "🇮🇩 Bahasa Indonesia",
      ms: "🇲🇾 Bahasa Melayu",
      tl: "🇵🇭 Filipino",
      bn: "🇧🇩 বাংলা",
      ur: "🇵🇰 اردو",
      fa: "🇮🇷 فارسی",
      he: "🇮🇱 עברית",
      ar: "🇸🇦 العربية",
      tr: "🇹🇷 Türkçe",
      az: "🇦🇿 Azərbaycan",
      ka: "🇬🇪 ქართული",
      hy: "🇦🇲 Հայերեն",
      kk: "🇰🇿 Қазақша",
      ky: "🇰🇬 Кыргызча",
      uz: "🇺🇿 O'zbek",
      tj: "🇹🇯 Тоҷикӣ",
      mn: "🇲🇳 Монгол",
      my: "🇲🇲 မြန်မာ",
      km: "🇰🇭 ខ្មែរ",
      lo: "🇱🇦 ລາວ",
      si: "🇱🇰 සිංහල",
      ne: "🇳🇵 नेपाली",
    },
  },
  americas: {
    name: "🌎 Americas",
    languages: {
      en: "🇺🇸 English",
      es: "🇪🇸 Español",
      pt: "🇧🇷 Português",
      fr: "🇨🇦 Français",
      qu: "🇵🇪 Quechua",
      gn: "🇵🇾 Guaraní",
      ht: "🇭🇹 Kreyòl Ayisyen",
    },
  },
  africa: {
    name: "🌍 Africa",
    languages: {
      ar: "🇪🇬 العربية",
      sw: "🇰🇪 Kiswahili",
      am: "🇪🇹 አማርኛ",
      ha: "🇳🇬 Hausa",
      yo: "🇳🇬 Yorùbá",
      ig: "🇳🇬 Igbo",
      zu: "🇿🇦 isiZulu",
      xh: "🇿🇦 isiXhosa",
      af: "🇿🇦 Afrikaans",
      fr: "🇸🇳 Français",
      pt: "🇦🇴 Português",
      mg: "🇲🇬 Malagasy",
      rw: "🇷🇼 Kinyarwanda",
      so: "🇸🇴 Soomaali",
      ti: "🇪🇷 ትግርኛ",
    },
  },
  oceania: {
    name: "🌊 Oceania",
    languages: {
      en: "🇦🇺 English",
      mi: "🇳🇿 Te Reo Māori",
      fj: "🇫🇯 Vosa Vakaviti",
      to: "🇹🇴 Lea Fakatonga",
      sm: "🇼🇸 Gagana Samoa",
      ty: "🇵🇫 Reo Tahiti",
      haw: "🏝️ ʻŌlelo Hawaiʻi",
    },
  },
} as const;

// Category display names
export const CATEGORY_NAMES = {
  [LanguageCategory.POPULAR]: "⭐ Popular Languages",
  [LanguageCategory.EUROPE]: "🇪🇺 Europe",
  [LanguageCategory.ASIA]: "🌏 Asia",
  [LanguageCategory.AMERICAS]: "🌎 Americas",
  [LanguageCategory.AFRICA]: "🌍 Africa",
  [LanguageCategory.OCEANIA]: "🌊 Oceania",
  [LanguageCategory.CUSTOM]: "✏️ Custom Language",
} as const;

// Comprehensive language display names mapping for utility functions
export const LANGUAGE_DISPLAY_NAMES = {
  en: "🇺🇸 English",
  ja: "🇯🇵 日本語",
  es: "🇪🇸 Español",
  fr: "🇫🇷 Français",
  de: "🇩🇪 Deutsch",
  it: "🇮🇹 Italiano",
  pt: "🇧🇷 Português",
  ru: "🇷🇺 Русский",
  zh: "🇨🇳 中文",
  ko: "🇰🇷 한국어",
  ar: "🇸🇦 العربية",
  hi: "🇮🇳 हिन्दी",
  th: "🇹🇭 ไทย",
  vi: "🇻🇳 Tiếng Việt",
  tr: "🇹🇷 Türkçe",
  pl: "🇵🇱 Polski",
  nl: "🇳🇱 Nederlands",
  sv: "🇸🇪 Svenska",
  no: "🇳🇴 Norsk",
  da: "🇩🇰 Dansk",
  fi: "🇫🇮 Suomi",
  cs: "🇨🇿 Čeština",
  hu: "🇭🇺 Magyar",
  ro: "🇷🇴 Română",
  bg: "🇧🇬 Български",
  hr: "🇭🇷 Hrvatski",
  sk: "🇸🇰 Slovenčina",
  sl: "🇸🇮 Slovenščina",
  et: "🇪🇪 Eesti",
  lv: "🇱🇻 Latviešu",
  lt: "🇱🇹 Lietuvių",
  el: "🇬🇷 Ελληνικά",
  he: "🇮🇱 עברית",
  fa: "🇮🇷 فارسی",
  ur: "🇵🇰 اردو",
  bn: "🇧🇩 বাংলা",
  ta: "🇮🇳 தமிழ்",
  te: "🇮🇳 తెలుగు",
  ml: "🇮🇳 മലയാളം",
  kn: "🇮🇳 ಕನ್ನಡ",
  gu: "🇮🇳 ગુજરાતી",
  pa: "🇮🇳 ਪੰਜਾਬੀ",
  mr: "🇮🇳 मराठी",
  ne: "🇳🇵 नेपाली",
  si: "🇱🇰 සිංහල",
  my: "🇲🇲 မြန်မာ",
  km: "🇰🇭 ខ្មែរ",
  lo: "🇱🇦 ລາວ",
  ka: "🇬🇪 ქართული",
  hy: "🇦🇲 Հայերեն",
  az: "🇦🇿 Azərbaycan",
  kk: "🇰🇿 Қазақша",
  ky: "🇰🇬 Кыргызча",
  uz: "🇺🇿 O'zbek",
  tj: "🇹🇯 Тоҷикӣ",
  mn: "🇲🇳 Монгол",
  id: "🇮🇩 Bahasa Indonesia",
  ms: "🇲🇾 Bahasa Melayu",
  tl: "🇵🇭 Filipino",
  sw: "🇰🇪 Kiswahili",
  am: "🇪🇹 አማርኛ",
  ha: "🇳🇬 Hausa",
  yo: "🇳🇬 Yorùbá",
  ig: "🇳🇬 Igbo",
  zu: "🇿🇦 isiZulu",
  xh: "🇿🇦 isiXhosa",
  af: "🇿🇦 Afrikaans",
  mg: "🇲🇬 Malagasy",
  rw: "🇷🇼 Kinyarwanda",
  so: "🇸🇴 Soomaali",
  ti: "🇪🇷 ትግርኛ",
  qu: "🇵🇪 Quechua",
  gn: "🇵🇾 Guaraní",
  ht: "🇭🇹 Kreyòl Ayisyen",
  mi: "🇳🇿 Te Reo Māori",
  fj: "🇫🇯 Vosa Vakaviti",
  to: "🇹🇴 Lea Fakatonga",
  sm: "🇼🇸 Gagana Samoa",
  ty: "🇵🇫 Reo Tahiti",
  haw: "🏝️ ʻŌlelo Hawaiʻi",
  mt: "🇲🇹 Malti",
  ga: "🇮🇪 Gaeilge",
  cy: "🏴󠁧󠁢󠁷󠁬󠁳󠁿 Cymraeg",
  eu: "🏴 Euskera",
  ca: "🏴 Català",
} as const;

// Language-specific greetings for UI
export const LANGUAGE_GREETINGS = {
  en: "👋",
  ja: "こんにちは 👋",
  es: "¡Hola! 👋",
  fr: "Bonjour 👋",
  de: "Hallo 👋",
  it: "Ciao 👋",
  pt: "Olá 👋",
  ru: "Привет 👋",
  zh: "你好 👋",
  ko: "안녕하세요 👋",
  ar: "مرحبا 👋",
  hi: "नमस्ते 👋",
  th: "สวัสดี 👋",
  vi: "Xin chào 👋",
  tr: "Merhaba 👋",
  pl: "Cześć 👋",
  nl: "Hallo 👋",
  sv: "Hej 👋",
  no: "Hei 👋",
  da: "Hej 👋",
  fi: "Hei 👋",
  cs: "Ahoj 👋",
  hu: "Szia 👋",
  ro: "Salut 👋",
  bg: "Здравей 👋",
  hr: "Bok 👋",
  sk: "Ahoj 👋",
  sl: "Živjo 👋",
  et: "Tere 👋",
  lv: "Sveiki 👋",
  lt: "Labas 👋",
  el: "Γεια σας 👋",
  he: "שלום 👋",
  fa: "سلام 👋",
  ur: "سلام 👋",
  bn: "নমস্কার 👋",
  my: "မင်္ဂလာပါ 👋",
  km: "សួស្តី 👋",
  lo: "ສະບາຍດີ 👋",
  ka: "გამარჯობა 👋",
  hy: "Բարև 👋",
  az: "Salam 👋",
  kk: "Сәлем 👋",
  ky: "Салам 👋",
  uz: "Salom 👋",
  tj: "Салом 👋",
  mn: "Сайн байна уу 👋",
  id: "Halo 👋",
  ms: "Hello 👋",
  tl: "Kumusta 👋",
  sw: "Hujambo 👋",
  am: "ሰላም 👋",
  ha: "Sannu 👋",
  yo: "Bawo 👋",
  ig: "Ndewo 👋",
  zu: "Sawubona 👋",
  xh: "Molo 👋",
  af: "Hallo 👋",
  qu: "Imaynalla 👋",
  gn: "Mba'éichapa 👋",
  ht: "Bonjou 👋",
  mi: "Kia ora 👋",
} as const;
